# Generated by Django 6.0.1 on 2026-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20),
        ),
    ]
