# Generated by Django 6.0.1 on 2026-04-20 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='fine_type',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='status',
        ),
        migrations.AddField(
            model_name='fine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='is_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.TextField(default='No reason provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
