# Generated by Django 6.0.1 on 2026-04-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_remove_fine_fine_type_remove_fine_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fine',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
