# Generated by Django 6.0.1 on 2026-04-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_wallet_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pending_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='refundable_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='entry_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='CREDIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('PAYMENT', 'Payment'), ('FINE', 'Fine Deduction'), ('DEPOSIT_PAYMENT', 'Security Deposit Payment'), ('DEPOSIT_RELEASE', 'Security Deposit Released'), ('WITHDRAWAL', 'Withdrawal')], max_length=20),
        ),
    ]
