# Generated by Django 6.0.3 on 2026-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Fine charged per day for late return (in INR)', max_digits=10),
        ),
    ]
