# Generated by Django 6.0.3 on 2026-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_add_late_fee_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Refundable deposit paid at booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Daily fine added for late returns', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Base price for 24-hour rental', max_digits=10),
        ),
    ]
