# Generated by Django 6.0.1 on 2026-04-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_add_security_deposit_to_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fine_per_hour',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Hourly fine added for late returns', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Base price for 1-hour rental', max_digits=10),
        ),
    ]
