# Generated by Django 6.0.1 on 2026-04-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_brand_vehicle_brand_str_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
