# Generated by Django 6.0.1 on 2026-04-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_brand_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, default='1200cc', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, default='Petrol', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.CharField(blank=True, default='15 km/pl', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, default='Manual', max_length=50, null=True),
        ),
    ]
