# Generated by Django 6.0.1 on 2026-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15, null=True),
        ),
    ]
