# Generated by Django 6.0.3 on 2026-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_ongoing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_return_date',
            field=models.DateField(blank=True, help_text='Actual date the vehicle was returned', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late return fine = late_days × vehicle.late_fee_per_day', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='fine_paid',
            field=models.BooleanField(default=False, help_text='True once user has paid the late fine'),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_days',
            field=models.IntegerField(default=0, help_text='Number of days returned after end_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ONGOING', 'Ongoing'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
