# Generated by Django 6.0.3 on 2026-04-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_late_return_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_file',
            field=models.FileField(blank=True, help_text='Stored PDF invoice generated after payment/completion', null=True, upload_to='invoices/'),
        ),
    ]
