# Generated by Django 6.0.3 on 2026-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='damage_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost for repairs found after return', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refund = Deposit - Fine - Damage (Max 0)', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ONGOING', 'Ongoing'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='late_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total = Rental + Deposit - Coupon', max_digits=10),
        ),
    ]
