# Generated by Django 6.0.1 on 2026-04-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_deposit_refund_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='actual_return_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('HOURLY', 'Hourly')], default='DAILY', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
