# Generated by Django 6.0.1 on 2026-04-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_released',
            field=models.BooleanField(default=False),
        ),
    ]
